local colors = {
    -- content here will not be touched
    -- PATCH_OPEN
Normal = {fg = "#D0CDC8", bg = "#11080D"},
Winseparator = {link = "Normal"},
["@boolean"] = {link = "Boolean"},
Character = {fg = "#DA9086"},
["@character"] = {link = "Character"},
CmpItemAbbrDeprecated = {fg = "#534E46", strikethrough = true},
CmpItemAbbrMatch = {fg = "#BC6C97", bold = true},
CmpItemAbbrMatchFuzzy = {fg = "#A68295"},
CmpItemKindFunction = {fg = "#E2ACBB"},
CmpItemKindInterface = {fg = "#AD677C"},
CmpItemKindKeyword = {fg = "#AD677C"},
CmpItemKindMethod = {fg = "#E2ACBB"},
CmpItemKindProperty = {fg = "#D0CDC8"},
CmpItemKindSnippet = {fg = "#F0CA93"},
CmpItemKindText = {fg = "#D0CDC8"},
CmpItemKindUnit = {fg = "#DA9086"},
CmpItemKindVariable = {fg = "#D0CDC8"},
CmpItemMenu = {fg = "#B9B4AC"},
ColorColumn = {bg = "#572942"},
Comment = {fg = "#534E46", italic = true},
["@comment"] = {link = "Comment"},
["@text.literal"] = {link = "Comment"},
Conceal = {},
["@conditional"] = {link = "Conditional"},
Constant = {fg = "#5478B6"},
Boolean = {link = "Constant"},
Float = {link = "Constant"},
Number = {link = "Constant"},
["@constant"] = {link = "Constant"},
["@lsp.type.enumMember"] = {link = "Constant"},
CurSearch = {fg = "#A69582", bg = "#341828"},
Cursor = {fg = "#11080D", bg = "#D0CDC8"},
CursorIM = {link = "Cursor"},
CursorColumn = {bg = "#2D281F"},
CursorLine = {bg = "#2D281F"},
CursorLineNr = {bg = "#2D281F"},
["@debug"] = {link = "Debug"},
["@define"] = {link = "Define"},
DiagnosticError = {fg = "#EA8476"},
DiagnosticFloatingError = {link = "DiagnosticError"},
DiagnosticSignError = {link = "DiagnosticError"},
DiagnosticVirtualTextError = {link = "DiagnosticError"},
DiagnosticHint = {fg = "#8295A6"},
DiagnosticInfo = {fg = "#8295A6"},
DiagnosticFloatingHint = {link = "DiagnosticInfo"},
DiagnosticFloatingInfo = {link = "DiagnosticInfo"},
DiagnosticSignHint = {link = "DiagnosticInfo"},
DiagnosticSignInfo = {link = "DiagnosticInfo"},
DiagnosticVirtualTextHint = {link = "DiagnosticInfo"},
DiagnosticVirtualTextInfo = {link = "DiagnosticInfo"},
DiagnosticOk = {fg = "#95A682"},
DiagnosticFloatingOk = {link = "DiagnosticOk"},
DiagnosticSignOk = {link = "DiagnosticOk"},
DiagnosticVirtualTextOk = {link = "DiagnosticOk"},
DiagnosticUnderlineError = {sp = "#DA9086", undercurl = true},
DiagnosticUnderlineHint = {sp = "#8295A6", undercurl = true},
DiagnosticUnderlineInfo = {sp = "#8295A6", undercurl = true},
DiagnosticUnderlineOk = {sp = "#95A682", undercurl = true},
DiagnosticUnderlineWarn = {sp = "#A69582", undercurl = true},
DiagnosticWarn = {fg = "#BC956C"},
DiagnosticFloatingWarn = {link = "DiagnosticWarn"},
DiagnosticSignWarn = {link = "DiagnosticWarn"},
DiagnosticVirtualTextWarn = {link = "DiagnosticWarn"},
DiffAdd = {bg = "#566845"},
DiffChange = {bg = "#572942"},
DiffDelete = {bg = "#784545"},
DiffText = {bg = "#433842"},
Directory = {fg = "#A68295"},
NeoTreeDirectoryIcon = {link = "Directory"},
NeoTreeDirectoryName = {link = "Directory"},
NvimTreeFolderIcon = {link = "Directory"},
NvimTreeFolderName = {link = "Directory"},
EndOfBuffer = {fg = "#524A3D"},
Error = {fg = "#EA8476"},
ErrorMsg = {fg = "#EA8476"},
Exception = {fg = "#EA8476"},
["@exception"] = {link = "Exception"},
["@float"] = {link = "Float"},
FloatBorder = {fg = "#A68295"},
TelescopeBorder = {link = "FloatBorder"},
WhichKeyBorder = {link = "FloatBorder"},
FloatTitle = {fg = "#EA8476"},
TelescopeTitle = {link = "FloatTitle"},
FoldColumn = {fg = "#534E46"},
CursorLineFold = {link = "FoldColumn"},
Folded = {fg = "#D0CDC8", bg = "#341828"},
Function = {fg = "#E2ACBB"},
["@function"] = {link = "Function"},
["@lsp.type.decorator"] = {link = "Function"},
["@lsp.type.function"] = {link = "Function"},
["@lsp.type.method"] = {link = "Function"},
["@method"] = {link = "Function"},
GitSignsAdd = {fg = "#95A682"},
NeoTreeGitAdded = {link = "GitSignsAdd"},
NvimTreeGitNew = {link = "GitSignsAdd"},
GitSignsAddInline = {bg = "#566845"},
GitSignsChange = {fg = "#A69582"},
NeoTreeGitModified = {link = "GitSignsChange"},
NvimTreeGitDirty = {link = "GitSignsChange"},
GitSignsChangeInline = {bg = "#433842"},
GitSignsDelete = {fg = "#DA9086"},
NeoTreeGitDeleted = {link = "GitSignsDelete"},
NvimTreeGitDeleted = {link = "GitSignsDelete"},
GitSignsDeleteInline = {bg = "#784545"},
IblIndent = {fg = "#2D281F"},
IndentBlanklineChar = {link = "IblIndent"},
IblScope = {fg = "#524A3D"},
IndentBlanklineContextChar = {link = "IblScope"},
Identifier = {fg = "#D0CDC8"},
["@field"] = {link = "Identifier"},
["@lsp.type.variable"] = {link = "Identifier"},
["@namespace"] = {link = "Identifier"},
["@property"] = {link = "Identifier"},
["@text.reference"] = {link = "Identifier"},
["@variable"] = {link = "Identifier"},
Ignore = {fg = "#534E46"},
IncSearch = {fg = "#11080D", bg = "#A68295"},
WildMenu = {link = "IncSearch"},
["@include"] = {link = "Include"},
["@keyword"] = {link = "Keyword"},
["@label"] = {link = "Label"},
LineNr = {fg = "#534E46"},
LineNrAbove = {link = "LineNr"},
LineNrBelow = {link = "LineNr"},
["@lsp.type.macro"] = {link = "Macro"},
["@macro"] = {link = "Macro"},
MatchParen = {fg = "#D0CDC8", bg = "#524A3D"},
ModeMsg = {fg = "#B9B4AC"},
MoreMsg = {fg = "#856397"},
MsgArea = {},
MsgSeparator = {fg = "#B9B4AC", bg = "#341828"},
NeoTreeFileIcon = {fg = "#D0CDC8"},
NeoTreeFileName = {fg = "#D0CDC8"},
NeoTreeFileNameOpened = {fg = "#BC6C97"},
NeoTreeIndentMarker = {fg = "#534E46"},
NvimTreeIndentMarker = {link = "NeoTreeIndentMarker"},
NeoTreeNormal = {fg = "#D0CDC8", bg = "#11080D"},
NeoTreeNormalNC = {link = "NeoTreeNormal"},
NvimTreeNormal = {link = "NeoTreeNormal"},
NeoTreeRootName = {fg = "#A68295", bold = true},
NvimTreeRootFolder = {link = "NeoTreeRootName"},
NonText = {fg = "#534E46"},
Whitespace = {link = "NonText"},
NormalFloat = {fg = "#D0CDC8"},
TelescopeNormal = {link = "NormalFloat"},
WhichKeyFloat = {link = "NormalFloat"},
NormalNC = {fg = "#D0CDC8", bg = "#11080D"},
NotifyDEBUGBorder = {fg = "#B9B4AC"},
NotifyDEBUGIcon = {fg = "#B9B4AC"},
NotifyDEBUGTitle = {fg = "#B9B4AC"},
NotifyERRORBorder = {fg = "#DA9086"},
NotifyERRORIcon = {fg = "#DA9086"},
NotifyERRORTitle = {fg = "#DA9086"},
NotifyINFOBorder = {fg = "#8295A6"},
NotifyINFOIcon = {fg = "#8295A6"},
NotifyINFOTitle = {fg = "#8295A6"},
NotifyTRACEBorder = {fg = "#856397"},
NotifyTRACEIcon = {fg = "#856397"},
NotifyTRACETitle = {fg = "#856397"},
NotifyWARNBorder = {fg = "#A69582"},
NotifyWARNIcon = {fg = "#A69582"},
NotifyWARNTitle = {fg = "#A69582"},
["@number"] = {link = "Number"},
NvimTreeOpenedFolderName = {fg = "#BC6C97"},
["@operator"] = {link = "Operator"},
Pmenu = {fg = "#B9B4AC", bg = "#341828"},
PmenuExtra = {link = "Pmenu"},
PmenuKind = {link = "Pmenu"},
PmenuSbar = {bg = "#2D281F"},
PmenuSel = {fg = "#BC6C97", bg = "#572942"},
PmenuExtraSel = {link = "PmenuSel"},
PmenuKindSel = {link = "PmenuSel"},
PmenuThumb = {bg = "#524A3D"},
PreProc = {fg = "#856397"},
Define = {link = "PreProc"},
Include = {link = "PreProc"},
Macro = {link = "PreProc"},
PreCondit = {link = "PreProc"},
["@preproc"] = {link = "PreProc"},
Question = {fg = "#BC956C"},
QuickFixLine = {fg = "#6C95BC"},
["@repeat"] = {link = "Repeat"},
Search = {bg = "#524A3D"},
SignColumn = {fg = "#D0CDC8", bg = "#11080D"},
CursorLineSign = {link = "SignColumn"},
Special = {fg = "#DA9086"},
Debug = {link = "Special"},
Delimiter = {link = "Special"},
SpecialChar = {link = "Special"},
SpecialComment = {link = "Special"},
Tag = {link = "Special"},
["@constructor"] = {link = "Special"},
["@string.escape"] = {link = "Special"},
["@string.special"] = {link = "Special"},
["@character.special"] = {link = "SpecialChar"},
SpecialKey = {fg = "#95A682"},
SpellBad = {sp = "#DA9086", undercurl = true},
SpellCap = {sp = "#856397", undercurl = true},
SpellLocal = {sp = "#B9B4AC", undercurl = true},
SpellRare = {sp = "#B9B4AC", undercurl = true},
Statement = {fg = "#AD677C"},
Conditional = {link = "Statement"},
Keyword = {link = "Statement"},
Label = {link = "Statement"},
Operator = {link = "Statement"},
Repeat = {link = "Statement"},
StatusLine = {fg = "#B9B4AC", bg = "#341828"},
StatusLineNC = {fg = "#534E46", bg = "#11080D"},
["@storageclass"] = {link = "StorageClass"},
String = {fg = "#F0CA93"},
["@string"] = {link = "String"},
["@structure"] = {link = "Structure"},
Substitute = {bg = "#524A3D"},
TabLine = {fg = "#B9B4AC", bg = "#341828"},
TabLineFill = {bg = "#341828"},
TabLineSel = {fg = "#11080D", bg = "#A68295"},
["@tag"] = {link = "Tag"},
TelescopeMatching = {fg = "#BC6C97", bold = true},
TelescopePreviewTitle = {fg = "#11080D", bg = "#856397"},
TelescopePromptBorder = {fg = "#A68295", bg = "#341828"},
TelescopePromptNormal = {bg = "#341828"},
TelescopePromptPrefix = {fg = "#A68295"},
TelescopePromptTitle = {fg = "#11080D", bg = "#A68295"},
TelescopeResultsTitle = {fg = "#D0CDC8", bg = "#572942"},
TelescopeSelection = {fg = "#D0CDC8", bg = "#524A3D"},
TelescopeSelectionCaret = {fg = "#A68295"},
TermCursor = {reverse = true},
TermCursorNC = {reverse = true},
Title = {fg = "#D0CDC8"},
Todo = {fg = "#DA9086"},
Type = {fg = "#AD677C"},
StorageClass = {link = "Type"},
Structure = {link = "Type"},
Typedef = {link = "Type"},
["@lsp.type.class"] = {link = "Type"},
["@lsp.type.enum"] = {link = "Type"},
["@lsp.type.interface"] = {link = "Type"},
["@lsp.type.struct"] = {link = "Type"},
["@lsp.type.type"] = {link = "Type"},
["@lsp.type.typeParameter"] = {link = "Type"},
["@type.definition"] = {link = "Typedef"},
Underlined = {underline = true},
VertSplit = {fg = "#524A3D"},
Visual = {bg = "#524A3D"},
VisualNOS = {link = "Visual"},
WarningMsg = {fg = "#BC956C"},
WhichKey = {fg = "#BC6C97"},
WhichKeyDesc = {fg = "#D0CDC8"},
WhichKeyGroup = {fg = "#856397"},
WhichKeySeparator = {fg = "#534E46"},
WinBar = {fg = "#B9B4AC", bg = "#341828", bold = true},
WinBarNC = {fg = "#B9B4AC", bg = "#341828"},
lCursor = {fg = "#11080D", bg = "#D0CDC8"},
netrwClassify = {fg = "#856397"},
["@constant.builtin"] = {fg = "#8295A6"},
["@constant.macro"] = {fg = "#8295A6"},
["@function.builtin"] = {fg = "#7B4C67"},
["@function.macro"] = {fg = "#7B4C67"},
["@lsp.type.namespace"] = {fg = "#856397"},
["@parameter"] = {fg = "#DA9086"},
["@lsp.type.parameter"] = {link = "@parameter"},
["@lsp.type.property"] = {link = "@property"},
["@punctuation"] = {fg = "#A68295"},
["@text.title"] = {fg = "#A68295"},
["@text.todo"] = {fg = "#95BC6C"},
["@text.underline"] = {underline = true},
["@text.uri"] = {fg = "#5478B6", underline = true},
["@type"] = {fg = "#DA9086"},
    -- PATCH_CLOSE
    -- content here will not be touched
}

-- colorschemes generally want to do this
vim.cmd("highlight clear")
vim.cmd("set t_Co=256")
vim.cmd("let g:colors_name='witchesbrew'")

-- apply highlight groups
for group, attrs in pairs(colors) do
    vim.api.nvim_set_hl(0, group, attrs)
end
